name: Cypress Tests

on:
  pull_request:
    branches:
      - main  # Replace with your default branch if it's different
  workflow_dispatch:
    inputs:
      browser:
        description: 'Please select browser for test run'
        required: true
        type: choice
        options:
          - chrome
          - firefox
          - edge
      environment:
        description: 'Please select environment for test run'
        required: true
        type: choice
        options:
          - prod
          - dev

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    env:
      PROD_URL: https://usadiscoveryprogram.com/
      DEV_URL: https://brand-usa-dev.netlify.app/
      BASE_URL: ${{ inputs.environment == 'dev' && env.DEV_URL || env.PROD_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Specify your Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ inputs.browser || 'chrome' }}
          start: npm start  # Adjust if you have a different command to start your app

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
